version: '2.1'

volumes:
  edudoor_data:
    external: true

services:
  edudoor_backend:
    container_name: edudoor_backend
    build:
      context: ../
      dockerfile: docker/Dockerfile
    links:
      - database
    volumes:
      - ../:/usr/app
    ports:
      - '5000:8080'
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: edudoor_backend_db
    restart: always
    build:
      context: ../
      dockerfile: docker/postgresql/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openolat
    ports:
      - '5433:5432'
    expose:
      - '5432'
    volumes:
      - edudoor_data:/var/lib/postgresql/edudoor
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
